dac-one-i2s-ctrl-objs := i2s_ctrl.o i2s_debug.o
dac-one-codec-objs := wm8960.o
# dac-one-codec-i2c-objs := i2c_wm8960.o
dac-one-i2s-objs := mt76xx_i2s.o
dac-one-pcm-objs := mt76xx_pcm.o
dac-one-machine-objs := mt76xx_machine.o
dac-one-gdma-objs := ralink_gdma.o

obj-m	+= dac-one-codec.o
# obj-m	+= dac-one-codec-i2c.o
obj-m	+= dac-one-i2s-ctrl.o
obj-m	+= dac-one-i2s.o
obj-m	+= dac-one-machine.o
obj-m	+= dac-one-pcm.o
obj-m	+= dac-one-gdma.o
